# Generated by Django 2.1.5 on 2020-02-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20200208_2154'),
        ('rango', '0004_auto_20200211_0059'),
        ('rango', '0002_auto_20200129_2302'),
    ]

    operations = [
    ]
